swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /message/:
    post:
      tags:
      - message
      description: rec message
      operationId: MessageController.Rec Message
      parameters:
      - in: body
        name: body
        description: The message content
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Message'
        "403":
          description: body is empty
definitions:
  models.Message:
    title: Message
    type: object
    properties:
      Content:
        type: string
tags:
- name: message
  description: |
    Operations about message
